<?php
/**
 * @file
 * drop_jobs_dev.context.inc
 */

/**
 * Implements hook_context_default_contexts().
 */
function drop_jobs_dev_context_default_contexts() {
  $export = array();

  $context = new stdClass();
  $context->disabled = FALSE; /* Edit this to true to make a default context disabled initially */
  $context->api_version = 3;
  $context->name = 'drop_jobs_dev';
  $context->description = 'Drop Jobs Development mode.';
  $context->tag = 'drop_jobs_dev';
  $context->conditions = array(
    'sitewide' => array(
      'values' => array(
        1 => 1,
      ),
    ),
  );
  $context->reactions = array(
    'block' => array(
      'blocks' => array(
        'masquerade-masquerade' => array(
          'module' => 'masquerade',
          'delta' => 'masquerade',
          'region' => 'footer_secondcolumn',
          'weight' => '-10',
        ),
        'devel-execute_php' => array(
          'module' => 'devel',
          'delta' => 'execute_php',
          'region' => 'footer_thirdcolumn',
          'weight' => '-10',
        ),
      ),
    ),
  );
  $context->condition_mode = 0;

  // Translatables
  // Included for use with string extractors like potx.
  t('Drop Jobs Development mode.');
  t('drop_jobs_dev');
  $export['drop_jobs_dev'] = $context;

  return $export;
}
