<?php
/**
 * @file
 * Drop Jobs Report installation hooks.
 */

/**
 * Implements hook_enable().
 */
function drop_jobs_report_enable() {
  // Rebuild the features static caches.
  features_include(TRUE);

  $module = 'drop_jobs_report';
  $feature = feature_load($module);
  $items[$module] = array_keys($feature->info['features']);
  _features_restore('enable', $items);
  _features_restore('rebuild', $items);
}
